import React from "react";
// import { describe } from "vitest";

// probably cy.wrap the initial button

describe("Quiz", () => {
    it('should start with a single button', () => {
        cy.visit('/')
        cy.get('button').should('contain.text', 'Start Quiz').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('[data-test="test-item-0"] button').click()
        cy.get('h2').should('contain.text', 'Quiz Completed')
        cy.get('div[class="alert alert-success"]').invoke('text').should('match', /Your Score: \d+\/10/i)
        
        cy.get('button').should('contain.text', 'Take New Quiz').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('[data-test="test-item-1"] button').click()
        cy.get('h2').should('contain.text', 'Quiz Completed')
        cy.get('div[class="alert alert-success"]').invoke('text').should('match', /Your Score: \d+\/10/i)
        
        cy.get('button').should('contain.text', 'Take New Quiz').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('[data-test="test-item-2"] button').click()
        cy.get('h2').should('contain.text', 'Quiz Completed')
        cy.get('div[class="alert alert-success"]').invoke('text').should('match', /Your Score: \d+\/10/i)
        cy.get('button').should('contain.text', 'Take New Quiz').click()

        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('[data-test="test-item-3"] button').click()
        cy.get('h2').should('contain.text', 'Quiz Completed')
        cy.get('div[class="alert alert-success"]').invoke('text').should('match', /Your Score: \d+\/10/i)
        cy.get('button').should('contain.text', 'Take New Quiz')
    })
})